### PR TITLE
add xml gamelist dat generator to mame menu

### PR DESCRIPTION
**Pull request by markwkidd**
This parallels my PR to the mame2003 prime repo: https://github.com/libretro/mame2003-libretro/pull/348

I have only tested this in Windows but it is working well there. If you are willing to add this to mame2003-plus it will facilitate testing the new ROM additions you have made.

### CODE REVIEW

**Comment by arcadez** [comment]
@markwkidd ok merged, BTW if I knew how i'd give you full access to this git then you can 
merge in or change whatever you want without running it by me firstly

**Comment by markwkidd** [comment]
Thank you. Although you may not want to give me full access yet since I seem to have made a mistake

Now I am building from your master and wondering why the new Generate XML DAT menu entry crashes the mame2003-plus core. 

Sorry about that! (This does not happen with regular mame2003)

I'll try to figure out what's going on

**Comment by markwkidd** [comment]
@arcadez can you see if the new xml generator is working for you in mame2003-plus when you press the Tab menu?

It seems like every change I made is identical to mame2003 except it crashes for me. I wonder if it is maybe because I am using RetroArch without a proper .info core file for mame2003-plus.

**Comment by grant2258** [comment]
i had this i was write perrmissisons check for errorno in the file open to avoid that because a file can open but not be writable and will segfault when you try write.

**Comment by grant2258** [comment]
log_cb() is causing the segfault comment them out or fix em little devils up

**Comment by markwkidd** [comment]
removed log_cb() with https://github.com/arcadez/-mame2003-plus-libretro/pull/10

**Comment by markwkidd** [comment]
Still crashing here

**Comment by grant2258** [comment]
remove the logging just comment it out for now mark i just added a printf for the else condition 

void generate_xml_dat()
{
        int pathcount = osd_get_path_count(FILETYPE_XML_DAT);
    osd_file *xml_dat_osd = osd_fopen(FILETYPE_XML_DAT, pathcount, "mame2003.xml", "w");
    FILE *xml_dat = xml_dat_osd->file;

    if (xml_dat == NULL)
//        log_cb(RETRO_LOG_ERROR, "Unable to open mame2003.xml for writing.\n");
        printf("test\n");
        else
        {
//              log_cb(RETRO_LOG_INFO, "Generating mame2003.xml\n");
                print_mame_xml(xml_dat, drivers);
                osd_fclose(xml_dat_osd);
        }
}

**Comment by markwkidd** [comment]
still crashing here with that patch @grant2258 even though the same code does not crash in mame2003-libretro

the last line in the log is a blank [libretro INFO] so I do think there some bad call to a log happening

**Comment by markwkidd** [comment]
that's a good clue actually

**Comment by markwkidd** [comment]
It's a segfault, it happens in the middle of outputting a line to the log via the libretro logging system. Even with those lines commented out. 

So maybe there is a line being logged that involves a variable that is not initialized or has gone out of scope. @arcadez are you set up with a debugger or something else that tipped you off to this being a problem with a log? In other words, are you able to pinpoint which log_cb call is triggering the segfault?

**Comment by grant2258** [comment]
it was me that  found the log_cb was causing the crash. What tipped me off was the warming when comping it

**Comment by markwkidd** [comment]
oh sorry I didn't mean to attributed. I was reading that in my email client and didn't read it correctly.

**Comment by grant2258** [comment]
mark try this

replace the logging comments  with printf for now

close emulation station so the screen can open from the console command

now run as root

 sudo/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003-plus/mame2003-plus_libretro.so --config /opt/retropie/configs/mame-libretro/retroarch.cfg "/home/pi/RetroPie/roms/mame-libretro/mame2003/88games.zip" --appendconfig /dev/shm/retroarch.cfg --verbose


this will rule out file permissions thats that only other thing that could cause a segfault here

**Comment by markwkidd** [comment]
I should tell you that I don't use RetroPie :) Actually someone recently gave me an rpi3 but I haven't had a chance to try it out.

I coordinate a lot with the retropie community but I'm working in Windows 7 and I can also boot to Ubuntu 17.04 when needed.

**Comment by markwkidd** [comment]
Also, I don't play video games much either. Lol.

**Comment by grant2258** [comment]
ah ok ill try this on a x64 machine will install and test there.  Well you should start playing games lol!

**Comment by markwkidd** [comment]
It's all coming out in the open. I build them for friends and family, then sometimes they invite me over and I play with them.

**Comment by grant2258** [comment]
sounds like a plan well ill change my comment to run mame2003 from and administrator command line prompt

**Pull request merged**
